name: PickyEater2
options:
  bundleIdPrefix: babubhaisab
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.8.1
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 7.10.2
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios.git
    from: 4.31.9
targets:
  PickyEater2:
    type: application
    platform: iOS
    sources:
      - path: PickyEater2
        excludes:
          - "Core/Sources/PickyEater2Core/**"
    dependencies:
      - target: PickyEater2Core
      - package: Alamofire
      - package: Kingfisher
      - package: RevenueCat
    settings:
      base:
        INFOPLIST_FILE: PickyEater2/Infrastructure/Configuration/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: babubhaisab.PickyEater2
        CODE_SIGN_ENTITLEMENTS: PickyEater2/Infrastructure/Configuration/PickyEater2.entitlements
        DEVELOPMENT_TEAM: K6UBSX4Q43
        SWIFT_VERSION: 5.0
  PickyEater2Core:
    type: framework
    platform: iOS
    sources:
      - path: PickyEater2/Core/Sources/PickyEater2Core
    dependencies:
      - package: Alamofire
      - package: Kingfisher
      - package: RevenueCat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: babubhaisab.PickyEater2Core
        DEVELOPMENT_TEAM: K6UBSX4Q43
        SWIFT_VERSION: 5.0
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        SKIP_INSTALL: NO
        INFOPLIST_FILE: PickyEater2/Core/Sources/PickyEater2Core/Info.plist
  PickyEater2Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PickyEater2Tests
    dependencies:
      - target: PickyEater2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: babubhaisab.PickyEater2Tests
        DEVELOPMENT_TEAM: K6UBSX4Q43
        SWIFT_VERSION: 5.0
  PickyEater2UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PickyEater2UITests
    dependencies:
      - target: PickyEater2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: babubhaisab.PickyEater2UITests
        DEVELOPMENT_TEAM: K6UBSX4Q43
        SWIFT_VERSION: 5.0 